#!/bin/bash
#PBS -S /bin/bash
#PBS -j oe
#PBS -V
#PBS -l nodes=1:ppn=8:gpus=1
project_dir=/home/xyzhang/research/ADBCVUMPS.jl
julia --project=${project_dir} ${project_dir}/job/Heisenberg-fold.jl --D 8 --chi 128 --folder ${project_dir}/data/ --opiter 1000